### ISSUE TITLE
矫正

### ISSUE THREAD

**Issue by Suiyueemperor** [guokaide/algorithm#4]
![image](https://user-images.githubusercontent.com/44223072/64236430-fc4e2080-cf2c-11e9-9f25-925179c0ada0.png)
O(1)

**Comment by dayAndnight2018** [comment]
> ![image](https://user-images.githubusercontent.com/44223072/64236430-fc4e2080-cf2c-11e9-9f25-925179c0ada0.png)
> O(1)

是你搞错咯！这个表述是没有错误的，因为先查询后插入，查询复杂度是O(n)的，查完插入复杂度是O(1)

**Comment by Suiyueemperor** [comment]
打扰了，我搞错了，对，先查询位置
